<#
.SYNOPSIS
    Content-hash integrity manifest for dotbot framework files.

.DESCRIPTION
    Pure utility module — generates and verifies a hash manifest of
    framework-owned files under a target project's .bot/ directory.

    The manifest (`.bot/.manifest.json`) is committed to git so it rides along
    on fresh clones and CI. It is regenerated by `dotbot init` and
    `dotbot init --force`, and checked by the 04-framework-integrity verify
    hook and the task-state MCP tools.

    Unlike a git-status check, hash verification catches tampering that was
    committed via `git commit --no-verify` — the gap identified in
    andresharpe/dotbot#173 comment 4237794998.

    Hashing semantics: the digest is SHA256 over file content with CR (0x0D)
    bytes stripped — equivalent to `sha256(cat file | tr -d '\r')`. This is
    deliberately NOT a raw-byte hash. Framework files can land on disk as
    CRLF or LF depending on git autocrlf, editor settings, `Set-Content` on
    Windows, and .gitattributes filtering. A raw-byte SHA256 would report
    every cross-platform clone as "tampered" for line-ending drift alone.
    Normalising in the hash itself makes integrity robust against any
    line-ending variance — no dependency on .gitattributes being correct, no
    constraint on how framework files are written on disk. The digest will
    therefore NOT match `Get-FileHash` or `sha256sum` on the file; that is
    intentional and documented.

    This module has NO dependency on FrameworkIntegrity.psm1. The canonical
    protected-paths list is passed IN by callers (FrameworkIntegrity.psm1,
    init-project.ps1), keeping the dependency one-way:
    FrameworkIntegrity -> Manifest (never the reverse).

.NOTES
    Canonical location: workflows/default/systems/mcp/modules/Manifest.psm1
    (alongside FrameworkIntegrity.psm1). Ships into target projects as
    .bot/systems/mcp/modules/Manifest.psm1 via the normal `dotbot init` copy
    of workflows/default/. FrameworkIntegrity.psm1 imports it as a sibling in
    both the source repo and the target project.
#>

function Get-FrameworkContentHash {
    <#
    .SYNOPSIS
        Computes a SHA256 hash of file content with CR (0x0D) bytes stripped.

    .DESCRIPTION
        The framework's integrity check cares whether file CONTENT changed, not
        whether the on-disk bytes differ by line-ending encoding. Stripping CR
        before hashing makes CRLF and LF versions of the same content produce
        the same digest.

        Implementation note: the file is decoded as Latin-1 (a 1:1 byte↔codepoint
        mapping for 0x00-0xFF) so that String.Replace — a native .NET operation —
        can strip CRs in a single pass without a per-byte PowerShell loop.
        SHA256.HashData and Convert.ToHexString are .NET 5+ static methods
        available in PowerShell 7 (dotbot's required runtime).

        PowerShell does NOT ship a built-in content-aware hash cmdlet;
        Get-FileHash is byte-level only. git hash-object would respect
        .gitattributes but depends on git having processed the file under the
        correct attribute rules — the dependency we're explicitly avoiding here.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    # .NET IO APIs use [Environment]::CurrentDirectory, which doesn't follow
    # PowerShell's Push-Location. Resolve to an absolute path so relative
    # callers (tests, CLI) work regardless of where they were invoked from.
    $resolved = (Resolve-Path -LiteralPath $Path).Path

    $bytes = [System.IO.File]::ReadAllBytes($resolved)
    $stripped = [System.Text.Encoding]::Latin1.GetString($bytes).Replace("`r", '')
    $filtered = [System.Text.Encoding]::Latin1.GetBytes($stripped)
    $digest   = [System.Security.Cryptography.SHA256]::HashData($filtered)
    return [System.Convert]::ToHexString($digest)
}

function Get-ManifestFileEntries {
    <#
    .SYNOPSIS
        Walks the protected paths under $ProjectRoot and yields (relpath, hash, size)
        for each regular file. Skips symlinks and junctions.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ProjectRoot,
        [Parameter(Mandatory)]
        [string[]]$ProtectedPaths
    )

    # Normalise $ProjectRoot to the OS-native form. $ProjectRoot can arrive
    # with forward slashes (e.g. from `git rev-parse --show-toplevel` on Windows)
    # while $_.FullName always has native slashes — GetFullPath collapses both
    # to a canonical absolute path so every downstream comparison is stable.
    $ProjectRoot = [System.IO.Path]::GetFullPath($ProjectRoot)

    # The manifest itself lives under .bot/ and may be in ProtectedPaths so
    # that git-status catches uncommitted edits, but we must never hash it
    # into itself (circular dependency — the hash changes on every write).
    $manifestRel = '.bot/.manifest.json'

    $entries = [ordered]@{}
    foreach ($rel in $ProtectedPaths) {
        $abs = Join-Path $ProjectRoot $rel
        if (-not (Test-Path -LiteralPath $abs)) { continue }

        $item = Get-Item -LiteralPath $abs -Force
        if ($item.LinkType) { continue }  # skip symlink/junction at the root

        if ($item -is [System.IO.DirectoryInfo]) {
            # Sort by relative path for deterministic manifest output across platforms.
            Get-ChildItem -LiteralPath $abs -Recurse -File -Force -ErrorAction SilentlyContinue |
                Where-Object { -not $_.LinkType } |
                Sort-Object { [System.IO.Path]::GetRelativePath($ProjectRoot, $_.FullName).Replace('\', '/') } |
                ForEach-Object {
                    $fileRel = [System.IO.Path]::GetRelativePath($ProjectRoot, $_.FullName).Replace('\', '/')
                    if ($fileRel -eq $manifestRel) { return }  # skip self-reference
                    $hash = Get-FrameworkContentHash -Path $_.FullName
                    $entries[$fileRel] = [ordered]@{
                        sha256 = $hash
                        size   = $_.Length
                    }
                }
        } elseif ($item -is [System.IO.FileInfo]) {
            $fileRel = [System.IO.Path]::GetRelativePath($ProjectRoot, $item.FullName).Replace('\', '/')
            if ($fileRel -eq $manifestRel) { continue }  # skip self-reference
            $hash = Get-FrameworkContentHash -Path $item.FullName
            $entries[$fileRel] = [ordered]@{
                sha256 = $hash
                size   = $item.Length
            }
        }
    }
    return $entries
}

function New-DotbotManifest {
    <#
    .SYNOPSIS
        Generates .bot/.manifest.json with SHA256 hashes of every framework file.

    .PARAMETER ProjectRoot
        Absolute path to the target project root (the directory containing .bot/).

    .PARAMETER ProtectedPaths
        Array of .bot/-relative paths to protect (e.g., '.bot/systems', '.bot/go.ps1').
        Callers obtain this from Get-FrameworkProtectedPaths in FrameworkIntegrity.psm1.

    .PARAMETER UserPaths
        Array of .bot/-relative paths that are safe for agents to edit
        (e.g., 'workspace/', '.control/', 'profile/'). Recorded in the manifest
        for documentation; not used for integrity checks.

    .PARAMETER Generator
        Free-form label recorded in the manifest. Defaults to "dotbot".

    .OUTPUTS
        The absolute path to the manifest file that was written.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ProjectRoot,
        [Parameter(Mandatory)]
        [string[]]$ProtectedPaths,
        [string[]]$UserPaths = @(),
        [string]$Generator = 'dotbot'
    )

    $botDir = Join-Path $ProjectRoot ".bot"
    if (-not (Test-Path -LiteralPath $botDir)) {
        throw "No .bot/ directory under $ProjectRoot"
    }

    $entries = Get-ManifestFileEntries -ProjectRoot $ProjectRoot -ProtectedPaths $ProtectedPaths

    $manifest = [ordered]@{
        version         = 1
        generated_at    = ([DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ'))
        generator       = $Generator
        protected_paths = @($ProtectedPaths)
        user_paths      = @($UserPaths)
        files           = $entries
    }

    $manifestPath = Join-Path $botDir ".manifest.json"
    $json = $manifest | ConvertTo-Json -Depth 10

    # Trailing newline for POSIX friendliness; UTF-8 without BOM.
    $json = $json + "`n"
    [System.IO.File]::WriteAllText($manifestPath, $json, [System.Text.UTF8Encoding]::new($false))
    return $manifestPath
}

function Test-DotbotManifest {
    <#
    .SYNOPSIS
        Verifies every file listed in .bot/.manifest.json still has a matching
        SHA256 hash. Also flags files under protected paths that aren't in the
        manifest (additions) and manifest entries missing on disk (deletions).

    .PARAMETER ProjectRoot
        Absolute path to the target project root.

    .PARAMETER ProtectedPaths
        Array of .bot/-relative paths to check for additions not in the manifest.
        Callers obtain this from Get-FrameworkProtectedPaths in FrameworkIntegrity.psm1.

    .OUTPUTS
        Hashtable with keys:
          success     — $true iff every file matches and no adds/missings
          reason      — 'clean' | 'tampered' | 'missing-manifest'
          message     — human-readable summary
          files       — array of relative paths flagged as tampered/missing/added
          remediation — follow-up instruction
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ProjectRoot,
        [Parameter(Mandatory)]
        [string[]]$ProtectedPaths
    )

    $manifestPath = Join-Path (Join-Path $ProjectRoot ".bot") ".manifest.json"
    if (-not (Test-Path -LiteralPath $manifestPath)) {
        return @{
            success     = $false
            reason      = 'missing-manifest'
            message     = '.bot/.manifest.json is missing'
            files       = @()
            remediation = 'Run: dotbot init --force'
        }
    }

    try {
        $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
    } catch {
        return @{
            success     = $false
            reason      = 'missing-manifest'
            message     = 'Failed to parse .bot/.manifest.json'
            files       = @()
            remediation = 'Run: dotbot init --force'
        }
    }

    $tampered = @()
    $missing  = @()

    # Verify each manifest entry exists on disk with matching hash.
    $manifestKeys = @{}
    foreach ($prop in $manifest.files.PSObject.Properties) {
        $rel = $prop.Name
        $manifestKeys[$rel] = $true
        $abs = Join-Path $ProjectRoot $rel
        if (-not (Test-Path -LiteralPath $abs)) {
            $missing += $rel
            continue
        }
        $item = Get-Item -LiteralPath $abs -Force
        if ($item.LinkType) { continue }  # symlinks not hashed
        $actual = Get-FrameworkContentHash -Path $abs
        if ($actual -ne $prop.Value.sha256) {
            $tampered += $rel
        }
    }

    # Detect files under protected paths that are NOT in the manifest (added).
    # Reuses Get-ManifestFileEntries to avoid duplicating the directory walk.
    $currentEntries = Get-ManifestFileEntries -ProjectRoot $ProjectRoot -ProtectedPaths $ProtectedPaths
    $added = @($currentEntries.Keys | Where-Object { -not $manifestKeys.ContainsKey($_) })

    $all = @($tampered + $missing + $added)
    if ($all.Count -eq 0) {
        return @{
            success     = $true
            reason      = 'clean'
            message     = 'Framework manifest verified'
            files       = @()
            remediation = ''
        }
    }

    $parts = @()
    if ($tampered.Count -gt 0) { $parts += "$($tampered.Count) tampered" }
    if ($missing.Count  -gt 0) { $parts += "$($missing.Count) missing" }
    if ($added.Count    -gt 0) { $parts += "$($added.Count) added" }

    return @{
        success     = $false
        reason      = 'tampered'
        message     = "Framework manifest mismatch ($($parts -join ', '))"
        files       = $all
        remediation = 'To update framework files: dotbot init --force. To discard changes: git checkout -- <file>'
    }
}

Export-ModuleMember -Function @(
    'Get-FrameworkContentHash',
    'New-DotbotManifest',
    'Test-DotbotManifest'
)
